# Generated by Django 4.2.7 on 2023-11-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('mrp', models.IntegerField()),
                ('sellPrice', models.IntegerField()),
                ('hsnCode', models.CharField(max_length=200)),
                ('gstPercent', models.IntegerField()),
                ('productCategory', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
            ],
        ),
    ]
